# 🐳 PRODUCTION CONTAINERIZATION TEMPLATE
# This is an EXAMPLE template that gets REPLACED during framework implementation
# The AI agent will DELETE this file and create production-ready CI/CD workflows

name: "[TEMPLATE] Production Container Pipeline"
# This workflow is DISABLED and serves as a template only
# The framework will generate actual production workflows that:
# ✅ Build optimized multi-stage Dockerfiles for each service
# ✅ Push to container registries with semantic versioning
# ✅ Include security scanning and vulnerability assessments
# ✅ Support multi-service matrix builds for microservices
# ✅ Implement rollback procedures and health checks
# ✅ Clean up this template file upon completion

# TEMPLATE STATUS: This file will be DELETED during implementation
# REPLACEMENT: Production workflows will be created in:
# - .github/workflows/build-and-deploy.yml (main pipeline)
# - .github/workflows/security-scan.yml (security checks)
# - .github/workflows/quality-gates.yml (linting, testing)

on:
  workflow_dispatch: # Manual trigger only - this is a template
    inputs:
      note:
        description: "This is a template file that gets replaced"
        required: false
        default: "Template will be deleted during implementation"

jobs:
  template-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Template Notification
        run: |
          echo "🐳 CONTAINERIZATION TEMPLATE"
          echo "This template file demonstrates the pattern but will be replaced"
          echo "The framework generates production-ready workflows that include:"
          echo "  ✅ Multi-stage Docker builds for optimal image size"
          echo "  ✅ Security scanning with Trivy/Snyk"
          echo "  ✅ Multi-architecture builds (amd64/arm64)"
          echo "  ✅ Semantic versioning and tagging strategies"
          echo "  ✅ Registry integration (Docker Hub/ACR/ECR/GHCR)"
          echo "  ✅ Quality gates and rollback procedures"
          echo "  ✅ Service-specific builds for microservices"
          echo ""
          echo "🗑️  This template will be DELETED during implementation"
          echo "🚀 Production workflows will be auto-generated based on:"
          echo "  - Project architecture (monolith/microservices)"
          echo "  - Technology stack detected"
          echo "  - Target deployment environment"
          echo "  - Security and compliance requirements"

  example-docker-pattern:
    runs-on: ubuntu-latest
    if: false # Disabled - this is just for reference
    steps:
      - uses: actions/checkout@v4

      # Modern Docker setup with latest versions
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Multi-registry login support
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.CONTAINER_REGISTRY || 'docker.io' }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Semantic versioning and tagging
      - name: Generate Tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.CONTAINER_REGISTRY }}/${{ vars.PROJECT_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      # Multi-stage build with caching
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Security scanning
      - name: Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.meta.outputs.tags }}
          format: "sarif"
          output: "trivy-results.sarif"
# FRAMEWORK IMPLEMENTATION NOTES:
# The AI agent will analyze the project and generate workflows that include:
# 1. Service detection and matrix builds for microservices
# 2. Technology-specific optimizations (Node.js, .NET, Python)
# 3. Environment-specific deployments (dev/staging/prod)
# 4. Integration with cloud providers (AWS/Azure/GCP)
# 5. Monitoring and observability setup
# 6. Automated rollback procedures
